[profile.default]
src = 'src'
out = 'out'
libs = ['lib']


offline = false 
auto_detect_solc = true
ignored_error_codes = [
    3420
]
solc_version = "0.8.19"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config